# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NoUo901uDUNLGRvad5kRZkJTa_OCXHC2
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install --upgrade --verbose git+https://github.com/Roaster05/EduAid-Clone.git

!pip install --quiet git+https://github.com/boudinfl/pke.git

!python -m nltk.downloader universal_tagset
!python -m spacy download en_core_web_sm

!wget https://github.com/explosion/sense2vec/releases/download/v1.0.0/s2v_reddit_2015_md.tar.gz

!tar -xvf  s2v_reddit_2015_md.tar.gz

!ls s2v_old

import nltk
nltk.download('stopwords')

from flask import Flask, request, jsonify
from Questgen import main

app = Flask(__name__)

qg = main.QGen()

@app.route('/predict_mcq', methods=['POST'])
def predict_mcq():
    data = request.get_json()
    input_text = data.get('text', '')
    output = qg.predict_mcq({'input_text': input_text})
    return jsonify({'output': output})

@app.route('/hello', methods=['GET'])
def hello():
    return 'Hello, this is a GET request response!'

if __name__ == '__main__':
    app.run()


